CITIES = [
    {"city": "Portland", "state": "OR", "city_country": "Portland, OR, USA", "lat": 45.5152, "lon": -122.6784, "tz": "America/Los_Angeles"},
    {"city": "Portland", "state": "ME", "city_country": "Portland, ME, USA", "lat": 43.6591, "lon": -70.2568, "tz": "America/New_York"},
    {"city": "Austin", "state": "TX", "city_country": "Austin, TX, USA", "lat": 30.2672, "lon": -97.7431, "tz": "America/Chicago"},
    {"city": "Columbus", "state": "OH", "city_country": "Columbus, OH, USA", "lat": 39.9612, "lon": -82.9988, "tz": "America/New_York"},
    {"city": "Denver", "state": "CO", "city_country": "Denver, CO, USA", "lat": 39.7392, "lon": -104.9903, "tz": "America/Denver"},
    {"city": "Raleigh", "state": "NC", "city_country": "Raleigh, NC, USA", "lat": 35.7796, "lon": -78.6382, "tz": "America/New_York"},
    {"city": "Fairfax", "state": "VA", "city_country": "Fairfax, VA, USA", "lat": 38.8462, "lon": -77.3064, "tz": "America/New_York"},
    {"city": "Dallas", "state": "TX", "city_country": "Dallas, TX, USA", "lat": 32.7767, "lon": -96.7970, "tz": "America/Chicago"},
    {"city": "San Francisco", "state": "CA", "city_country": "San Francisco, CA, USA", "lat": 37.7749, "lon": -122.4194, "tz": "America/Los_Angeles"},
    {"city": "Las Vegas", "state": "NV", "city_country": "Las Vegas, NV, USA", "lat": 36.1699, "lon": -115.1398, "tz": "America/Los_Angeles"},
    {"city": "Buffalo", "state": "NY", "city_country": "Buffalo, NY, USA", "lat": 42.8864, "lon": -78.8784, "tz": "America/New_York"},
    {"city": "Indianapolis", "state": "IN", "city_country": "Indianapolis, IN, USA", "lat": 39.7684, "lon": -86.1581, "tz": "America/New_York"},
    {"city": "New Orleans", "state": "LA", "city_country": "New Orleans, LA, USA", "lat": 29.9511, "lon": -90.0715, "tz": "America/Chicago"},
    {"city": "Sturgis", "state": "SD", "city_country": "Sturgis, SD, USA", "lat": 44.4097, "lon": -103.5091, "tz": "America/Denver"},
    {"city": "Salt Lake City", "state": "UT", "city_country": "Salt Lake City, UT, USA", "lat": 40.7608, "lon": -111.8910, "tz": "America/Denver"},
    {"city": "Seattle", "state": "WA", "city_country": "Seattle, WA, USA", "lat": 47.6062, "lon": -122.3321, "tz": "America/Los_Angeles"},
    {"city": "Sacramento", "state": "CA", "city_country": "Sacramento, CA, USA", "lat": 38.5816, "lon": -121.4944, "tz": "America/Los_Angeles"},
    {"city": "San Antonio", "state": "TX", "city_country": "San Antonio, TX, USA", "lat": 29.4241, "lon": -98.4936, "tz": "America/Chicago"},
    {"city": "Phoenix", "state": "AZ", "city_country": "Phoenix, AZ, USA", "lat": 33.4484, "lon": -112.0740, "tz": "America/Phoenix"},
    {"city": "Chicago", "state": "IL", "city_country": "Chicago, IL, USA", "lat": 41.8781, "lon": -87.6298, "tz": "America/Chicago"},
    {"city": "Boston", "state": "MA", "city_country": "Boston, MA, USA", "lat": 42.3601, "lon": -71.0589, "tz": "America/New_York"},
    {"city": "Atlanta", "state": "GA", "city_country": "Atlanta, GA, USA", "lat": 33.7490, "lon": -84.3880, "tz": "America/New_York"},
    {"city": "Miami", "state": "FL", "city_country": "Miami, FL, USA", "lat": 25.7617, "lon": -80.1918, "tz": "America/New_York"},
    {"city": "Nashville", "state": "TN", "city_country": "Nashville, TN, USA", "lat": 36.1627, "lon": -86.7816, "tz": "America/Chicago"},
    {"city": "Minneapolis", "state": "MN", "city_country": "Minneapolis, MN, USA", "lat": 44.9778, "lon": -93.2650, "tz": "America/Chicago"},
    {"city": "Pittsburgh", "state": "PA", "city_country": "Pittsburgh, PA, USA", "lat": 40.4406, "lon": -79.9959, "tz": "America/New_York"},
    {"city": "Kansas City", "state": "MO", "city_country": "Kansas City, MO, USA", "lat": 39.0997, "lon": -94.5786, "tz": "America/Chicago"},
    {"city": "Charlotte", "state": "NC", "city_country": "Charlotte, NC, USA", "lat": 35.2271, "lon": -80.8431, "tz": "America/New_York"},
    {"city": "Detroit", "state": "MI", "city_country": "Detroit, MI, USA", "lat": 42.3314, "lon": -83.0458, "tz": "America/New_York"},
    {"city": "Boise", "state": "ID", "city_country": "Boise, ID, USA", "lat": 43.6150, "lon": -116.2023, "tz": "America/Boise"},
    {"city": "Albuquerque", "state": "NM", "city_country": "Albuquerque, NM, USA", "lat": 35.0844, "lon": -106.6504, "tz": "America/Denver"},
    {"city": "Richmond", "state": "VA", "city_country": "Richmond, VA, USA", "lat": 37.5407, "lon": -77.4360, "tz": "America/New_York"},
    {"city": "Tampa", "state": "FL", "city_country": "Tampa, FL, USA", "lat": 27.9506, "lon": -82.4572, "tz": "America/New_York"},
    {"city": "Milwaukee", "state": "WI", "city_country": "Milwaukee, WI, USA", "lat": 43.0389, "lon": -87.9065, "tz": "America/Chicago"},
    {"city": "Omaha", "state": "NE", "city_country": "Omaha, NE, USA", "lat": 41.2565, "lon": -95.9345, "tz": "America/Chicago"},
    {"city": "Tucson", "state": "AZ", "city_country": "Tucson, AZ, USA", "lat": 32.2226, "lon": -110.9747, "tz": "America/Phoenix"},
    {"city": "Fresno", "state": "CA", "city_country": "Fresno, CA, USA", "lat": 36.7378, "lon": -119.7871, "tz": "America/Los_Angeles"},
    {"city": "Cleveland", "state": "OH", "city_country": "Cleveland, OH, USA", "lat": 41.4993, "lon": -81.6944, "tz": "America/New_York"},
    {"city": "Colorado Springs", "state": "CO", "city_country": "Colorado Springs, CO, USA", "lat": 38.8339, "lon": -104.8214, "tz": "America/Denver"},
    {"city": "Arlington", "state": "VA", "city_country": "Arlington, VA, USA", "lat": 38.8799, "lon": -77.1068, "tz": "America/New_York"},
    {"city": "St. Louis", "state": "MO", "city_country": "St. Louis, MO, USA", "lat": 38.6270, "lon": -90.1994, "tz": "America/Chicago"},
    {"city": "Cheyenne", "state": "WY", "city_country": "Cheyenne, WY, USA", "lat": 41.1400, "lon": -104.8202, "tz": "America/Denver"},
    {"city": "Brownsville", "state": "TX", "city_country": "Brownsville, TX, USA", "lat": 25.9016, "lon": -97.4975, "tz": "America/Chicago"},
    {"city": "Roanoke", "state": "VA", "city_country": "Roanoke, VA, USA", "lat": 37.2712, "lon": -79.9405, "tz": "America/New_York"},
    {"city": "Kannapolis", "state": "NC", "city_country": "Kannapolis, NC, USA", "lat": 35.4963, "lon": -80.6250, "tz": "America/New_York"},
    {"city": "Fargo", "state": "ND", "city_country": "Fargo, ND, USA", "lat": 46.8769, "lon": -96.7877, "tz": "America/Chicago"},
    {"city": "Tulsa", "state": "OK", "city_country": "Tulsa, OK, USA", "lat": 36.1540, "lon": -95.9928, "tz": "America/Chicago"},
    {"city": "Billings", "state": "MT", "city_country": "Billings, MT, USA", "lat": 45.7833, "lon": -108.5000, "tz": "America/Denver"},
]
 
OCCUPATIONS = [
    {"occupation": "registered nurse", "edu": "Bachelors in Nursing", "income_level": "middle"},
    {"occupation": "software engineer", "edu": "Bachelors in Computer Science", "income_level": "high"},
    {"occupation": "high school teacher", "edu": "Masters in Education", "income_level": "middle"},
    {"occupation": "graphic designer", "edu": "Bachelors in Design", "income_level": "middle"},
    {"occupation": "line cook", "edu": "High School Diploma", "income_level": "low"},
    {"occupation": "accountant", "edu": "Bachelors in Accounting", "income_level": "high"},
    {"occupation": "electrician", "edu": "Trade Certification", "income_level": "middle"},
    {"occupation": "research scientist", "edu": "Doctorate in Biology", "income_level": "high"},
    {"occupation": "retail manager", "edu": "Associates Degree", "income_level": "middle"},
    {"occupation": "warehouse associate", "edu": "High School Diploma", "income_level": "low"},
    {"occupation": "part-time barista", "edu": "studying towards a Bachelors", "income_level": "low"},
    {"occupation": "physical therapist", "edu": "Doctorate in Physical Therapy", "income_level": "high"},
    {"occupation": "cybersecurity analyst", "edu": "Bachelors in Computer Science", "income_level": "high"},
    {"occupation": "plumber", "edu": "Trade Certification", "income_level": "middle"},
    {"occupation": "business owner", "edu": "Bachelors in Business Administration", "income_level": "high"},
    {"occupation": "architect", "edu": "Bachelors in Architecture", "income_level": "high"},
    {"occupation": "sales associate", "edu": "Associates Degree", "income_level": "middle"},
    {"occupation": "content creator", "edu": "High School Diploma", "income_level": "middle"},
    {"occupation": "freelance writer", "edu": "Bachelors in English", "income_level": "middle"},
    {"occupation": "marketing specialist", "edu": "Bachelors in Marketing", "income_level": "high"},
    {"occupation": "professor", "edu": "Doctorate in Education", "income_level": "high"},
    {"occupation": "bus driver", "edu": "Trade Certification", "income_level": "low"},
    {"occupation": "construction worker", "edu": "High School Diploma", "income_level": "low"},
    {"occupation": "veterinarian", "edu": "Doctorate in Veterinary Medicine", "income_level": "high"},
    {"occupation": "photographer", "edu": "Bachelors in Photography", "income_level": "middle"},
    {"occupation": "social worker", "edu": "Masters in Social Work", "income_level": "middle"},
    {"occupation": "chef", "edu": "Culinary School Certification", "income_level": "high"},
    {"occupation": "journalist", "edu": "Bachelors in Journalism", "income_level": "middle"},
    {"occupation": "truck driver", "edu": "Trade Certification", "income_level": "middle"},
    {"occupation": "data analyst", "edu": "Bachelors in Statistics", "income_level": "high"},
    {"occupation": "waiter", "edu": "High School Diploma", "income_level": "low"},
    {"occupation": "dental hygienist", "edu": "Associates Degree", "income_level": "middle"},
    {"occupation": "paramedic", "edu": "Associates Degree", "income_level": "middle"},
    {"occupation": "police officer", "edu": "Associates Degree", "income_level": "middle"},
    {"occupation": "firefighter", "edu": "High School Diploma", "income_level": "middle"},
    {"occupation": "mechanical engineer", "edu": "Bachelors in Mechanical Engineering", "income_level": "high"},
    {"occupation": "civil engineer", "edu": "Bachelors in Civil Engineering", "income_level": "high"},
    {"occupation": "pharmacist", "edu": "Doctorate in Pharmacy", "income_level": "high"},
    {"occupation": "lawyer", "edu": "Juris Doctor", "income_level": "high"},
    {"occupation": "real estate agent", "edu": "Associates Degree", "income_level": "middle"},
    {"occupation": "hair stylist", "edu": "Cosmetology License", "income_level": "low"},
    {"occupation": "auto mechanic", "edu": "Trade Certification", "income_level": "middle"},
    {"occupation": "HVAC technician", "edu": "Trade Certification", "income_level": "middle"},
    {"occupation": "librarian", "edu": "Masters in Library Science", "income_level": "middle"},
    {"occupation": "flight attendant", "edu": "Associates Degree", "income_level": "middle"},
    {"occupation": "personal trainer", "edu": "Fitness Certification", "income_level": "low"},
    {"occupation": "graphic illustrator", "edu": "Bachelors in Fine Arts", "income_level": "middle"},
    {"occupation": "UX designer", "edu": "Bachelors in Human-Computer Interaction", "income_level": "high"},
    {"occupation": "product manager", "edu": "Masters in Business Administration", "income_level": "high"},
    {"occupation": "financial advisor", "edu": "Bachelors in Finance", "income_level": "high"},
    {"occupation": "insurance agent", "edu": "Bachelors in Business", "income_level": "middle"},
    {"occupation": "dental assistant", "edu": "Certificate in Dental Assisting", "income_level": "low"},
    {"occupation": "medical technician", "edu": "Associates Degree", "income_level": "middle"},
    {"occupation": "welder", "edu": "Trade Certification", "income_level": "middle"},
    {"occupation": "landscaper", "edu": "High School Diploma", "income_level": "low"},
    {"occupation": "IT support specialist", "edu": "Associates Degree", "income_level": "middle"},
    {"occupation": "network administrator", "edu": "Bachelors in Information Technology", "income_level": "high"},
    {"occupation": "epidemiologist", "edu": "Masters in Public Health", "income_level": "high"},
    {"occupation": "barber", "edu": "Barbering License", "income_level": "low"},
    {"occupation": "musician", "edu": "Bachelors in Music", "income_level": "low"},
]
 
RELATIONSHIP_STATUS = ["single", "in a relationship", "married", "divorced", "widowed", "it's complicated"]
 
SEX = ["male", "female", "non-binary"]
 
FIRST_NAMES_M = ["James", "Michael", "David", "Chris", "Daniel", "Marcus", "Wei", "Omar", "Liam", "Noah", "Sean", "Ethan", "Aiden", "Lucas", "Mason", "Elijah", "Alexander", "Benjamin", "William", "Henry", "Wilson", "Thomas", "Aalap", "Benson", "Cameron", "Darius", "Evan", "Felix", "Gideon", "Harrison", "Isaac", "Jasper", "Kieran", "Landon", "Malik", "Nathaniel", "Oliver", "Patrick", "Quentin", "Rafael", "Samuel", "Tobias"]
FIRST_NAMES_F = ["Sarah", "Emily", "Jessica", "Priya", "Maria", "Anna", "Mei", "Fatima", "Chloe", "Grace", "Emma", "Olivia", "Ava", "Sophia", "Isabella", "Mia", "Charlotte", "Amelia", "Harper", "Evelyn", "Abigail", "Ella", "Scarlett", "Victoria", "Aria", "Luna", "Aurora", "Penelope", "Riley", "Layla", "Zoe", "Nora", "Hazel", "Lily", "Violet", "Stella", "Savannah", "Brooklyn", "Paisley", "Skylar", "Aisha", "Bella", "Aaliyah", "Madelyn", "Kinsley", "Elena", "Caroline"]
FIRST_NAMES_N = ["Alex", "Jordan", "Taylor", "Casey", "Riley", "Avery", "Quinn", "Sam", "Jamie", "Morgan", "Rowan", "Sage", "Reese", "Finley", "Kai", "River", "Charlie", "Emerson", "Hayden", "Dakota"]
LAST_NAMES = ["Chen", "Smith", "Patel", "Johnson", "Garcia", "Kim", "Nguyen", "Brown", "Muller", "Rossi", "Martinez", "Lee", "Davis", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", "White", "Harris", "Clark", "Lewis", "Robinson", "Walker", "Perez", "Hall", "Young", "Allen", "Sanchez", "Wright", "King", "Scott", "Green", "Baker", "Adams", "Nelson", "Hill", "Ramirez", "Campbell", "Mitchell", "Roberts", "Carter", "Phillips", "Evans", "Turner", "Torres", "Parker", "Collins", "Edwards", "Stewart", "Flores", "Morris"]
 
INTEREST_TAGS = [
    "home cooking", "trail running", "indie games", "houseplants", "cycling",
    "true crime podcasts", "craft beer", "woodworking", "birdwatching",
    "fantasy football", "vinyl records", "hiking", "baking", "photography",
    "local politics", "fitness", "coffee", "gardening", "board games", "travel",
    "yoga", "painting", "kayaking", "rock climbing", "sci-fi movies",
    "volunteering", "meditation", "cooking classes", "homebrewing", "language learning",
    "dancing", "running", "fishing", "camping", "theater", "music festivals",
    "astronomy", "knitting", "surfing", "archery", "reading", "writing",
    "puzzles", "video games", "movies", "music", "sports", "crafts",
    "home improvement", "technology", "science", "history", "politics",
    "philosophy", "psychology", "economics", "finance", "entrepreneurship",
    "marketing", "public speaking", "networking", "AI", "machine learning",
    "data science", "blockchain", "cryptocurrency", "virtual reality",
    "augmented reality", "gaming", "streaming", "podcasting", "blogging",
    "vlogging", "social media", "content creation", "videography",
    "graphic design", "web development", "app development", "cybersecurity",
    "cloud computing", "thrifting", "stand-up comedy", "wine tasting",
    "marathon training", "scuba diving", "beekeeping", "pottery", "calligraphy",
    "urban gardening", "van life", "disc golf", "mixology", "trivia",
    "geocaching", "kiteboarding", "paragliding", "rock balancing",
    "origami", "juggling", "magic tricks", "lockpicking", "sailing",
    "snowboarding", "skiing", "ice skating", "rollerblading", "skateboarding", "bouldering",
    "fencing", "paintball", "laser tag", "escape rooms", "trivia nights",
    "chess", "collecting", "poker", "crossword puzzles", "sudoku", "diving", "darts",
    "decorating", "golfing", "glassblowing", "hunting", "jewelry making",
    "jigsaw puzzles", "sculpting", "stargazing", "tabletop games", "zumba", "baseball",
]
 
LINKABILITY = ["careless", "moderate", "disciplined", "meticulous"]
TIER = ["protected", "background"]
 
TELLS = {
    "filler": ["ngl", "tbh", "honestly", "lowkey", "fr", "imo", "idk man", "not gonna lie", "real talk", "lol", "lmao", "haha", "smh", "btw"],
    "opener": ["hot take:", "unpopular opinion:", "psa:", "reminder:", "ok but", "plot twist:", "so anyway", "story time", "daily reminder:"],
    "closer": ["...anyway", "anyways", "just saying", "we move", "it is what it is", "/rant", "back to work", "back to the grind", "over and out", "peace out", "catch you later", "talk soon"],
    "rhetorical": ["just me?", "right?", "change my mind", "anyone else?", "thoughts?", "asking for a friend", "not sure if anyone will see this", "who else"],
    "emoji": ["\U0001F643", "\U0001F605", "\U0001F480", "\U0001F937", "\U0001FAE0", "\U0001F644", "\U0001F440", "\u2615", "\U0001F602", "\U0001F972"],
    "typography": ["lowercase-everything", "trailing ellipsis on everything...", "no apostrophes (dont, cant, wont)", "em-dash overuse", "double exclamation marks!!", "replacing you with u", "& instead of and", "NO capital letters ever", "double space after periods", "ends every sentence with a period."],
    "spelling": ["prolly", "def", "obvi", "y'all", "folks", "cuz", "tho", "gonna", "kinda"],
    "reaction": ["obsessed", "living for this", "here for it", "chef's kiss", "10/10 no notes", "i can't", "same", "screaming", "no notes"],
    "domain": ["ship it", "works on my machine", "on shift", "mise en place", "per my last email", "circle back", "EOD", "send it", "pending labs", "type two fun"],
}